/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class net_smackem_ylang_interop_Yln */

#ifndef _Included_net_smackem_ylang_interop_Yln
#define _Included_net_smackem_ylang_interop_Yln
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     net_smackem_ylang_interop_Yln
 * Method:    convolveImage
 * Signature: (II[III[F)[I
 */
JNIEXPORT jintArray JNICALL Java_net_smackem_ylang_interop_Yln_convolveImage
  (JNIEnv *, jobject, jint, jint, jintArray, jint, jint, jfloatArray);

/*
 * Class:     net_smackem_ylang_interop_Yln
 * Method:    convolveKernel
 * Signature: (II[FII[F)[F
 */
JNIEXPORT jfloatArray JNICALL Java_net_smackem_ylang_interop_Yln_convolveKernel
  (JNIEnv *, jobject, jint, jint, jfloatArray, jint, jint, jfloatArray);

/*
 * Class:     net_smackem_ylang_interop_Yln
 * Method:    composeImages
 * Signature: (II[I[II)[I
 */
JNIEXPORT jintArray JNICALL Java_net_smackem_ylang_interop_Yln_composeImages
  (JNIEnv *, jobject, jint, jint, jintArray, jintArray, jint);

/*
 * Class:     net_smackem_ylang_interop_Yln
 * Method:    composeKernels
 * Signature: (II[F[FI)[F
 */
JNIEXPORT jfloatArray JNICALL Java_net_smackem_ylang_interop_Yln_composeKernels
  (JNIEnv *, jobject, jint, jint, jfloatArray, jfloatArray, jint);

#ifdef __cplusplus
}
#endif
#endif
